# Теория вероятностей и математическая статистика
## Практикум 3


**Правила:**

* Дедлайн ** 24 декабря 2021 в 24:00**. После дедлайна работы не принимаются, кроме случаев наличия уважительной причины.
* Выполненную работу нужно отправить на почту MarkashevaVA@mgppu.ru, указав тему письма `"Практикум 3[номер группы] Фамилия Имя"`. Квадратные скобки обязательны.
* Прислать нужно ноутбук и его pdf-версию (без архивов). Названия файлов должны быть такими: `N.ipynb` и `N.pdf`, где `N` - ваш  номер в журнале группы и ФИО(нумерация начинается с 01,02,03... и т.д.)
* Решения, размещенные на каких-либо интернет-ресурсах не принимаются. Кроме того, публикация решения в открытом доступе может быть приравнена к предоставлению возможности списать.
* Для выполнения задания используйте этот ноутбук в качествие основы, ничего не удаляя из него.
* Никакой код из данного задания при проверке запускаться не будет.

*НЕЛЬЗЯ ИСПОЛЬЗОВАТЬ ЦИКЛЫ, кроме самых отчаянных ситуаций.

### Номер ВАШЕГО ВАРИАНТА есть номер вашей фамилии в списке группы. В дальнейшем будем обозначать его $N$

Весь код в авторском решении задания выполняется за полминуты.

In [108]:
import numpy as np
import scipy.stats as sps
import ipywidgets as widgets
import matplotlib.pyplot as plt

%matplotlib inline

# **Задача 1.** В этой задаче вам нужно исследовать свойства метаматического ожидания для указанного распределения.

А именно, 

Шаг1. 

Следует создать код для функции, которая будет считать математическое ожидание **произвольной** ДИСКРЕТНОЙ случайной величины $\xi$, в случае, если ДИСКРЕТНАЯ СЛУЧАЙНАЯ ВЕЛИЧИНА $\xi$ задана в виде таблицы функции распределения.

Шаг2. 

Следует создать код для функции, которая будет считать математическое ожидание случайной величины вида $f(\xi)$, зная таблицу функции распределения **произвольной** случайной величины $\xi$ и функцию $f(\cdot)$.

Шаг 3.

Используя полученный код Вам следует посчитать математическое ожидание  $\xi$ и $f(\xi)$, для двух случайных величин вашего варианта, и для всех функций вашего варианта. 

Должно получиться 10 чисел.

Сделайте выводы, письменно ответьте на вопросы:
Верно ли, что $E(f(\xi))=f(E\xi)$? Для какого вида функций это верно всегда?
Почему для других неверно?



# Начало
Использовались таблицы 5-ого и 79-ого вариантов, функции тоже 5 вариант

# Задание 1

**Шаг 1**

In [109]:
# заранее обозначу заданные функции (для упрощения дальнейших вычислений)

def f1(x): # 5x^2+2
    return 5*(x**2)+2

def f2(x): # sin(x)
    return np.sin(x)

def f3(x): # ln(x)+2
    return np.log(x)+2

def f4(x): # 5x+2
    return 5*x+2

# также укажу распределения 

# вариант распределения №5
x5 = np.array([1, 4, 6, 7, 12, 27, 28, 29.5, 30, 31.9, 32, 
               39, 39.1, 39.2, 39.3, 39.4, 40, 41, 42, 50])

p5 = np.array([2/105, 3/105, 4/105, 25/105, 6/105, 7/105, 7/105, 5/105, 6/105, 7/105, 
               8/105, 10/105, 1/105, 1/105, 1/105, 1/105, 1/105, 1/105, 4/105, 5/105])

# вариант распределения №79
x79 = np.array([-1, -4, -6, 7, 12, -27, 28, 29.5, 30, 31.9, 
                32, 39, 39.1, 39.2, 39.3, 39.4, 40, 41, 42, 50])

p79 = np.array([21/1130, 15/1130, 14/1130, 11/1130, 26/1130, 37/1130, 37/1130, 45/1130, 16/1130, 27/1130, 
                18/1130, 25/1130, 11/1130, 11/1130, 21/1130, 726/1130, 11/1130, 11/1130, 14/1130, 33/1130])

In [110]:
def ExpValue (x, p): #функция для вычисления математического ожидания, на вход получает таблицу распределения
    return np.sum(x*p)

**Шаг 2**

In [111]:
def ExpValueFun (f, xi, pi): #математическое ожидание при применении функции к таблице распределения
    xi = np.array(list(map(lambda x:f(x), xi)))
    return ExpValue(xi,pi)

def FunExp (f, x, p): #выполнение заданной функции от математического ожидания
    return f(ExpValue(x,p))

**Шаг 3**

In [112]:
print("Математическое ожидание для 5 таблицы =", ExpValue(x5, p5))
print("Математическое ожидание для 74 таблицы =", ExpValue(x79, p79))
print()

Математическое ожидание для 5 таблицы = 24.02666666666666
Математическое ожидание для 74 таблицы = 33.54053097345132



In [113]:
#функция 1
print("Мат. ожидание вида f(5x^2+2) для 5 распределения =", ExpValueFun(f1, x5, p5))
print("Значение функции 5x^2+2 от мат. ожидания для распределения 5 =", FunExp(f1, x5, p5))
print()
print("Мат. ожидание вида f(5x^2+2) для 79 распределения =", ExpValueFun(f1, x79, p79))
print("Значение функции 5x^2+2 от мат. ожидания для распределения 79 =", FunExp(f1, x79, p79))

Мат. ожидание вида f(5x^2+2) для 5 распределения = 3913.89619047619
Значение функции 5x^2+2 от мат. ожидания для распределения 5 = 2888.403555555554

Мат. ожидание вида f(5x^2+2) для 79 распределения = 6793.935044247788
Значение функции 5x^2+2 от мат. ожидания для распределения 79 = 5626.836089905237


In [114]:
#функция 2
print("Мат. ожидание вида f(sin(x)) для 5 распределения =", ExpValueFun(f2, x5, p5))
print("Значение функции sin(x) от мат. ожидания для распределения 5 =", FunExp(f2, x5, p5))
print()
print("Мат. ожидание вида f(sin(x)) для 79 распределения =", ExpValueFun(f2, x79, p79))
print("Значение функции sin(x) от мат. ожидания для распределения 79 =", FunExp(f2, x79, p79))

Мат. ожидание вида f(sin(x)) для 5 распределения = 0.25092949369796297
Значение функции sin(x) от мат. ожидания для распределения 5 = -0.8939462980408864

Мат. ожидание вида f(sin(x)) для 79 распределения = 0.6208583187427602
Значение функции sin(x) от мат. ожидания для распределения 79 = 0.8505278944873309


In [115]:
#функция 3
print("Мат. ожидание вида f(ln(x)+2) для 5 распределения =", ExpValueFun(f3, x5, p5))
print("Значение функции ln(x)+2 от мат. ожидания для распределения 5 =", FunExp(f3, x5, p5))
print()
print("Мат. ожидание вида f(ln(x)+2) для 79 распределения =", ExpValueFun(f3, x79, p79))
print("Значение функции ln(x)+2 от мат. ожидания для распределения 79 =", FunExp(f3, x79, p79))

Мат. ожидание вида f(ln(x)+2) для 5 распределения = 4.893345906167908
Значение функции ln(x)+2 от мат. ожидания для распределения 5 = 5.179164324631973

Мат. ожидание вида f(ln(x)+2) для 79 распределения = nan
Значение функции ln(x)+2 от мат. ожидания для распределения 79 = 5.512754587320776


<ipython-input-109-1c52d61cea9e>:10: RuntimeWarning: invalid value encountered in log
  return np.log(x)+2


In [116]:
#функция 4
print("Мат. ожидание вида f(5х+2) для 5 распределения =", ExpValueFun(f4, x5, p5))
print("Значение функции 5х+2 от мат. ожидания для распределения 5 =", FunExp(f4, x5, p5))
print()
print("Мат. ожидание вида f(5х+2) для 79 распределения =", ExpValueFun(f4, x79, p79))
print("Значение функции 5х+2 от мат. ожидания для распределения 79 =", FunExp(f4, x79, p79))

Мат. ожидание вида f(5х+2) для 5 распределения = 122.13333333333334
Значение функции 5х+2 от мат. ожидания для распределения 5 = 122.1333333333333

Мат. ожидание вида f(5х+2) для 79 распределения = 169.70265486725663
Значение функции 5х+2 от мат. ожидания для распределения 79 = 169.7026548672566


**Вывод**

Из выше проведенных вычислений становится понятно следующее:
1. Выражение $E(f(\xi))=f(E\xi)$ является верным, когда функция f задана линейно, как, например, 4-ая функция f(x)=5*x + 2
2. В случае с функцией ln(x)+2 и 79 вариантом распределения, в котором Х принимает отрицательные значения, мы вовсе не можем проверить выполнение данного равенства, т.к. выражение под логарифмом не может быть меньше нуля.

**Задача 2.** В этой задаче вам нужно исследовать свойства дисперсии для указанного распределения случайной величины.



Шаг 1.

Следует создать код для функции, которая будет считать дисперсию произвольной ДИСКРЕТНОЙ случайной величины $\xi$ ПО ОПРЕДЕЛЕНИЮ ДИСПЕРСИИ, в случае, если ДИСКРЕТНАЯ СЛУЧАЙНАЯ ВЕЛИЧИНА $\xi$ задана в виде таблицы функции распределения.

Шаг2. 

Следует создать код для функции, которая будет считать дисперсию и среднеквадратичное отклонение случайной величины вида $\xi$ ПО ФОРМУЛЕ (смотри свойства дисперсии в конспекте лекций), зная таблицу функции распределения случайной величины $\xi$.


Шаг 3.


Используя полученный код Вам следует посчитать ДИСПЕРСИИ для заданных в Вашем варианте двух случайных величин $\xi$, и для всех функций $f(\xi)$ вашего варианта **способом шага 1 и способом шага 2, и сравнить.**

Шаг 4.

Своими словами сформулирорвать выводы.


# Задание 2

**Шаг 1**

In [117]:
# Все нижеописанные функции возвращают значения дисперсий и среднеквадратическое отклонение для определенных аргументов 
# в виде (Дисперсия, Отклонение)

# способ расчета дисперсии по формуле D(x)=M(x^2)−(M(x))^2

def Var_simple_1(x, p): # функция для расчета дисперсии для заданной таблицы
    var = ExpValue(x**2, p) - ExpValue(x,p)**2
    return var, np.sqrt(var) 
 
def Variance_1(f, xi, pi): # функция для расчета дисперсии при применении функции к таблице
    xi = np.array(list(map(lambda x:f(x), xi)))
    var = ExpValue(xi**2, pi) - ExpValue(xi,pi)**2
    return var, np.sqrt(var) 

**Шаг 2**

In [118]:
# способ расчета дисперсии по формуле D(x)=M(x−M(x))^2

def Var_simple_2(x, p): # функция для расчета дисперсии для заданной таблицы
    var = ExpValue((x-ExpValue(x,p))**2,p)
    return var, np.sqrt(var)

def Variance_2(f, xi, pi): # функция для расчета дисперсии при применении функции к таблице
    xi = np.array(list(map(lambda x:f(x), xi)))
    var = ExpValue((xi-ExpValue(xi,pi))**2,pi)
    return var, np.sqrt(var)


**Шаг 3**

In [119]:
# расчеты дисперсий для распределений заданных таблицами

print("Для таблицы 5, 1 формула", Var_simple_1(x5, p5))
print("Для таблицы 5, 2 формула", Var_simple_1(x5, p5))
print()
print("Для таблицы 79, 1 формула", Var_simple_1(x79, p79))
print("Для таблицы 79, 2 формула", Var_simple_1(x79, p79))

Для таблицы 5, 1 формула (205.09852698412726, 14.321261361490729)
Для таблицы 5, 2 формула (205.09852698412726, 14.321261361490729)

Для таблицы 79, 1 формула (233.41979086851006, 15.278082041555807)
Для таблицы 79, 2 формула (233.41979086851006, 15.278082041555807)


In [120]:
# расчеты дисперсии для 1 функции

print("Для функции 5x^2+2, 5 таблица, 1 формула", Variance_1(f1, x5, p5))
print("Для функции 5x^2+2, 5 таблица, 2 формула", Variance_2(f1, x5, p5))
print()
print("Для функции 5x^2+2, 79 таблица, 1 формула", Variance_1(f1, x79, p79))
print("Для функции 5x^2+2, 79 таблица, 2 формула", Variance_2(f1, x79, p79))

Для функции 5x^2+2, 5 таблица, 1 формула (11889405.464604538, 3448.1017190048988)
Для функции 5x^2+2, 5 таблица, 2 формула (11889405.464604536, 3448.1017190048983)

Для функции 5x^2+2, 79 таблица, 1 формула (5972907.812541805, 2443.9533163589285)
Для функции 5x^2+2, 79 таблица, 2 формула (5972907.812541811, 2443.95331635893)


In [121]:
# расчеты дисперсии для 2 функции

print("Для функции sin(x), 5 таблица, 1 формул", Variance_1(f2, x5, p5))
print("Для функции sin(x), 5 таблица, 2 формула", Variance_2(f2, x5, p5))
print()
print("Для функции sin(x), 79 таблица, 1 формула", Variance_1(f2, x79, p79))
print("Для функции sin(x), 79 таблица, 2 формула", Variance_2(f2, x79, p79))

Для функции sin(x), 5 таблица, 1 формул (0.45738944922573754, 0.6763057365021663)
Для функции sin(x), 5 таблица, 2 формула (0.4573894492257375, 0.6763057365021662)

Для функции sin(x), 79 таблица, 1 формула (0.4465423704010896, 0.6682382587079922)
Для функции sin(x), 79 таблица, 2 формула (0.44654237040108946, 0.6682382587079921)


In [122]:
# расчеты дисперсии для 3 функции

print("Для функции log(x)+2, 5 таблица, 1 формул", Variance_1(f3, x5, p5))
print("Для функции log(x)+2, 5 таблица, 2 формула", Variance_2(f3, x5, p5))
print()
print("Для функции log(x)+2, 79 таблица, 1 формула", Variance_1(f3, x79, p79))
print("Для функции log(x)+2, 79 таблица, 2 формула", Variance_2(f3, x79, p79))

Для функции log(x)+2, 5 таблица, 1 формул (0.758737928278169, 0.8710556401735592)
Для функции log(x)+2, 5 таблица, 2 формула (0.7587379282781608, 0.8710556401735544)

Для функции log(x)+2, 79 таблица, 1 формула (nan, nan)
Для функции log(x)+2, 79 таблица, 2 формула (nan, nan)


<ipython-input-109-1c52d61cea9e>:10: RuntimeWarning: invalid value encountered in log
  return np.log(x)+2


In [123]:
# расчеты дисперсии для 4 функции

print("Для функции 5x+2, 5 таблица, 1 формул", Variance_1(f4, x5, p5))
print("Для функции 5x+2, 5 таблица, 2 формула", Variance_2(f4, x5, p5))
print()
print("Для функции 5x+2, 79 таблица, 1 формула", Variance_1(f4, x79, p79))
print("Для функции 5x+22, 79 таблица, 2 формула", Variance_2(f4, x79, p79))

Для функции 5x+2, 5 таблица, 1 формул (5127.4631746031755, 71.60630680745359)
Для функции 5x+2, 5 таблица, 2 формула (5127.463174603175, 71.60630680745359)

Для функции 5x+2, 79 таблица, 1 формула (5835.494771712747, 76.39041020777901)
Для функции 5x+22, 79 таблица, 2 формула (5835.494771712742, 76.39041020777897)


**Шаг 4**

Анализ результатов дает понять - формулы подсчета значений дисперсии приводят к одинаковым результатам. В случае с 3 функцией, которая задана логарифмически, невозможно вычислить дисперсию, т.к. математического ожидания для нее не существует по причинам, описанным в выводе к первому заданию. 

ПОДСКАЗКИ. Хорошо бы использовать  map, которое применяет функию к каждому элементу массива. НАПРИМЕР:


In [13]:
x = map(lambda tmp: tmp ** 2, range(5))
print(list(x))

[0, 1, 4, 9, 16]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [14]:
b=[1,2,5,3,4]
print(np.sort(b))
print(b)

[1 2 3 4 5]
[1, 2, 5, 3, 4]


Сумма и произведение всех элементов массива; максимальный и минимальный элемент;

In [15]:
b.sum(), b.prod(), b.max(), b.min()

AttributeError: 'list' object has no attribute 'sum'

Имеются встроенные функции для работы с массивами $\sqrt(\cdot),\ \exp(\cdot),\ \ln(\cdot),\ \sin(\cdot)$ и числа $e$ и $\pi$

In [16]:
print(np.sqrt(b))
print(np.exp(b))

print(np.sin(b))
print(np.e, np.pi)
print(np.log(y))

[1.         1.41421356 2.23606798 1.73205081 2.        ]
[  2.71828183   7.3890561  148.4131591   20.08553692  54.59815003]
[ 0.84147098  0.90929743 -0.95892427  0.14112001 -0.7568025 ]
2.718281828459045 3.141592653589793


NameError: name 'y' is not defined

Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое уже было.

In [17]:
print(y.cumsum())

NameError: name 'y' is not defined

ПРИМЕР РЕШЕНИЯ ПЕРВОЙ ЗАДАЧИ

In [18]:
freq=[0.36, 0.08, 0.02, 0.04, 0.1,0.1,0.1,0.1,0.1] # создаем массив вероятностей
variants= np.arange(1, 10, 1)  #создаем массив вариант
print(variants)


[1 2 3 4 5 6 7 8 9]
